[package]
name = "rechnung"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cqrs-es = "0.4.2"
axum = "0.6.4"
rusty-money = "0.4.1"
hyper = { version = "0.14", features = ["full"] }
mime = "0.3"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = "0.4.24"

[dev-dependencies]
tower = { version = "0.4", features = ["util"] }