[package]
name = "rechnung"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.4"
hyper = { version = "0.14", features = ["full"] }
mime = "0.3"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tower = { version = "0.4", features = ["util"] }